# Generated by Django 3.1.6 on 2021-03-28 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210112_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authpin',
            options={'verbose_name': 'Authentication PIN', 'verbose_name_plural': 'Authentication PINs'},
        ),
        migrations.AlterModelOptions(
            name='payclaim',
            options={'verbose_name': 'Payment Claim', 'verbose_name_plural': 'Payment Claims'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Withdrawal Request', 'verbose_name_plural': 'Withdrawal Requests'},
        ),
        migrations.AlterField(
            model_name='authpin',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL, verbose_name='Ordering Client'),
        ),
        migrations.AlterField(
            model_name='authpin',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Generation Date'),
        ),
        migrations.AlterField(
            model_name='authpin',
            name='is_invalid',
            field=models.BooleanField(default=False, verbose_name='Invalidated By Admin'),
        ),
        migrations.AlterField(
            model_name='authpin',
            name='pin',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=72, primary_key=True, serialize=False, unique=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='authpin',
            name='used',
            field=models.BooleanField(default=False, editable=False, verbose_name='PIN used'),
        ),
        migrations.AlterField(
            model_name='authpin',
            name='withdraw_request',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqs', to='main.withdrawalrequest', verbose_name='Matching Withdrawal Request '),
        ),
    ]
